# Generated by Django 4.2.13 on 2024-05-25 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='paid_completed',
            new_name='paid_students',
        ),
    ]
